# Average annual temperatures in F and wind speed in mph, us city capitals
capital_weather_data = {
    ("38", "-77"): {"temperature": 58, "windspeed": 10, "city": "Washington, DC"},
    ("32", "-86"): {"temperature": 62, "windspeed": 8, "city": "Montgomery"},
    ("58", "-134"): {"temperature": 42, "windspeed": 12, "city": "Juneau"},
    ("33", "-112"): {"temperature": 75, "windspeed": 9, "city": "Phoenix"},
    ("34", "-92"): {"temperature": 61, "windspeed": 7, "city": "Little Rock"},
    ("38", "-121"): {"temperature": 61, "windspeed": 8, "city": "Sacramento"},
    ("39", "-104"): {"temperature": 50, "windspeed": 10, "city": "Denver"},
    ("41", "-73"): {"temperature": 51, "windspeed": 9, "city": "Hartford"},
    ("39", "-75"): {"temperature": 55, "windspeed": 9, "city": "Dover"},
    ("30", "-84"): {"temperature": 68, "windspeed": 8, "city": "Tallahassee"},
    ("33", "-84"): {"temperature": 63, "windspeed": 8, "city": "Atlanta"},
    ("21", "-157"): {"temperature": 77, "windspeed": 12, "city": "Honolulu"},
    ("43", "-116"): {"temperature": 52, "windspeed": 9, "city": "Boise"},
    ("40", "-89"): {"temperature": 52, "windspeed": 10, "city": "Springfield"},
    ("39", "-86"): {"temperature": 52, "windspeed": 9, "city": "Indianapolis"},
    ("41", "-93"): {"temperature": 47, "windspeed": 10, "city": "Des Moines"},
    ("39", "-95"): {"temperature": 54, "windspeed": 10, "city": "Topeka"},
    ("38", "-84"): {"temperature": 55, "windspeed": 8, "city": "Frankfort"},
    ("30", "-91"): {"temperature": 67, "windspeed": 7, "city": "Baton Rouge"},
    ("44", "-69"): {"temperature": 48, "windspeed": 11, "city": "Augusta"},
    ("39", "-76"): {"temperature": 55, "windspeed": 9, "city": "Annapolis"},
    ("42", "-71"): {"temperature": 51, "windspeed": 10, "city": "Boston"},
    ("42", "-84"): {"temperature": 49, "windspeed": 10, "city": "Lansing"},
    ("44", "-93"): {"temperature": 45, "windspeed": 11, "city": "Saint Paul"},
    ("32", "-90"): {"temperature": 64, "windspeed": 8, "city": "Jackson"},
    ("38", "-92"): {"temperature": 54, "windspeed": 9, "city": "Jefferson City"},
    ("46", "-112"): {"temperature": 46, "windspeed": 10, "city": "Helena"},
    ("40", "-96"): {"temperature": 52, "windspeed": 10, "city": "Lincoln"},
    ("39", "-119"): {"temperature": 50, "windspeed": 9, "city": "Carson City"},
    ("43", "-71"): {"temperature": 48, "windspeed": 10, "city": "Concord"},
    ("40", "-74"): {"temperature": 55, "windspeed": 9, "city": "Trenton"},
    ("35", "-106"): {"temperature": 54, "windspeed": 10, "city": "Santa Fe"},
    ("42", "-73"): {"temperature": 49, "windspeed": 9, "city": "Albany"},
    ("35", "-78"): {"temperature": 60, "windspeed": 8, "city": "Raleigh"},
    ("46", "-100"): {"temperature": 41, "windspeed": 12, "city": "Bismarck"},
    ("39", "-83"): {"temperature": 53, "windspeed": 9, "city": "Columbus"},
    ("35", "-97"): {"temperature": 60, "windspeed": 10, "city": "Oklahoma City"},
    ("45", "-123"): {"temperature": 53, "windspeed": 8, "city": "Salem"},
    ("40", "-76"): {"temperature": 52, "windspeed": 9, "city": "Harrisburg"},
    ("41", "-71"): {"temperature": 51, "windspeed": 10, "city": "Providence"},
    ("34", "-81"): {"temperature": 63, "windspeed": 7, "city": "Columbia"},
    ("44", "-100"): {"temperature": 45, "windspeed": 11, "city": "Pierre"},
    ("36", "-87"): {"temperature": 59, "windspeed": 8, "city": "Nashville"},
    ("30", "-97"): {"temperature": 70, "windspeed": 9, "city": "Austin"},
    ("40", "-111"): {"temperature": 52, "windspeed": 9, "city": "Salt Lake City"},
    ("44", "-72"): {"temperature": 48, "windspeed": 10, "city": "Montpelier"},
    ("37", "-78"): {"temperature": 57, "windspeed": 8, "city": "Richmond"},
    ("47", "-122"): {"temperature": 53, "windspeed": 8, "city": "Olympia"},
    ("38", "-81"): {"temperature": 55, "windspeed": 8, "city": "Charleston"},
    ("43", "-89"): {"temperature": 48, "windspeed": 10, "city": "Madison"},
    ("41", "-104"): {"temperature": 48, "windspeed": 11, "city": "Cheyenne"},
    ("64", "-21"): {"temperature": 41, "windspeed": 13, "city": "Reykjavik"},
    ("59", "18"): {"temperature": 43, "windspeed": 11, "city": "Stockholm"},
    ("60", "25"): {"temperature": 42, "windspeed": 10, "city": "Helsinki"},
    ("59", "10"): {"temperature": 45, "windspeed": 12, "city": "Oslo"},
    ("55", "37"): {"temperature": 41, "windspeed": 9, "city": "Moscow"},
    ("45", "-73"): {"temperature": 42, "windspeed": 10, "city": "Ottawa"},
    ("39", "116"): {"temperature": 50, "windspeed": 9, "city": "Beijing"},
    ("50", "14"): {"temperature": 47, "windspeed": 8, "city": "Prague"},
    ("52", "21"): {"temperature": 46, "windspeed": 9, "city": "Warsaw"},
    ("47", "19"): {"temperature": 48, "windspeed": 8, "city": "Budapest"},
    ("46", "7"): {"temperature": 49, "windspeed": 7, "city": "Bern"},
    ("53", "-6"): {"temperature": 49, "windspeed": 11, "city": "Dublin"},
    ("55", "-3"): {"temperature": 47, "windspeed": 12, "city": "Edinburgh"},
    ("35", "69"): {"temperature": 54, "windspeed": 7, "city": "Kabul"},
    ("51", "-114"): {"temperature": 39, "windspeed": 10, "city": "Astana"},
    ("13", "100"): {"temperature": 84, "windspeed": 6, "city": "Bangkok"},
    ("12", "77"): {"temperature": 82, "windspeed": 7, "city": "Georgetown"},
    ("14", "121"): {"temperature": 83, "windspeed": 6, "city": "Quezon City"},
    ("6", "106"): {"temperature": 83, "windspeed": 7, "city": "Jakarta"},
    ("1", "32"): {"temperature": 81, "windspeed": 7, "city": "Khartoum"},
    ("23", "58"): {"temperature": 88, "windspeed": 8, "city": "Muscat"},
    ("7", "81"): {"temperature": 82, "windspeed": 7, "city": "Colombo"},
}


def get_location_lat_long_temp_wspd(lat, long):

    if (lat, long) in capital_weather_data:
        city_data = capital_weather_data[(lat, long)]
        return city_data
    else:
        return {}


if __name__ == "__main__":
    lat, long = "42", "50"
    print(get_location_lat_long_temp_wspd(lat, long))
